SELECT 
B.INCIDENTID
,C.NAME RULE_NAME
,E.DISCOVERURL FILE_LOCATION
,SUM(A.VIOLATIONCOUNT) TOTAL_MATCH_COUNT
FROM CONDITIONVIOLATION A

LEFT OUTER JOIN INCIDENT B ON A.INCIDENTID = B.INCIDENTID
LEFT OUTER JOIN DETECTIONRULE C ON B.POLICYID = C.POLICYID AND A.CONDITIONID = C.TOPLEVELCONDITIONID
LEFT OUTER JOIN POLICY D ON C.POLICYID = D.POLICYID
LEFT OUTER JOIN DISCOVERITEM E ON E.DISCOVERITEMID = B.DISCOVERITEMID

WHERE C.NAME LIKE 'RULE_IN_QUESTION'
AND D.NAME LIKE 'POLICY_IN_QUESTION'

GROUP BY B.INCIDENTID, C.NAME, D.NAME, E.DISCOVERURL
; 
