SELECT

B.NAME
,SUM(A.NUMBERRETRIEVEDFILES) Files_Scanned
,SUM(A.ITEMSFILTERED) FILES_FILTERED
,SUM(A.ITEMSFILTERED + A.NUMBERRETRIEVEDFILES) TOTAL_FILES
,SUM (TRUNC(BYTESSCANNED*1e-9 ,2))as GB_SCANNED

FROM WALK A
LEFT OUTER JOIN SCANASSIGNMENT B ON B.COURSEID = A.COURSEID
GROUP BY B.NAME;
